### ISSUE TITLE
Static files not getting modified inside docker container

### ISSUE THREAD

**Issue by TareqMonwer** [TareqMonwer/Django-School-Management#47]
After changing something in static files, it doesn't update the container on build command. No errors are given as well.
Maybe this is happening because docker/docker-compose configured improperly.

**Comment by AvTe** [comment]
> 
> 
> After changing something in static files, it doesn't update the container on build command. No errors are given as well.
> Maybe this is happening because docker/docker-compose configured improperly.





  



  **1.if you are bringing up the containers via docker-compose you can remove**

-  RUN mkdir /www
- 
-     WORKDIR /www
- 
-     COPY . /www/

 **2.from your web Dockerfile since you're mounting the volume in the composer file**

I would think you'd be trying to serve static files from your nginx container, so you'd docker exec` -it <nginx_container>` bash and making sure the files were copied to /static and /media there right?
